### ISSUE TITLE
UnicodeEncodeError / UnicodeDecodeError

### ISSUE THREAD

**Issue by salah93** [crosscompute/crosscompute#1]
File ".../crosscompute/types/__init__.py", line 126, in prepare_file_path
    f.write(file_content)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

my set up:
cc.ini:
```
[crosscompute]
command_template = python3 quran.py
                        --target_folder {target_folder}
                        -O {ayah_text_path}
```

when running `crosscompute serve`, entering unicode text into the text_path, and submitting form
this issue occurs

**Comment by salah93** [comment]
File "/Users/salah/.virtualenvs/crosscompute/lib/python2.7/site-packages/crosscompute/types/path.jinja2", line 11, in template
    {{ render_query(tool_argument_noun) }}
  File "/Users/salah/.virtualenvs/crosscompute/lib/python2.7/site-packages/crosscompute_text/type.jinja2", line 9, in template
    <textarea name="{{ key }}_txt" id="{{ key }}_" class="form-control" rows="10">{{ format_value(key) }}</textarea>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)


this occurs when giving text_path a default value:
cc.ini:
```
[crosscompute]
command_template = python3 quran.py
                        --target_folder {target_folder}
                        -O {ayah_text_path}
ayah_text_path = tests/ayah.txt
```

**Comment by AShoydokova** [comment]
Did you try to enter u'tests/ayah.txt'?

**Comment by salah93** [comment]
Just tried it now,
Crosscompute reads the Unicode symbol u'...' as part of the path so it searches for a file literally named u'...'

**Comment by salah93** [comment]
This could be a fix if Roy implements it

**Comment by invisibleroads** [comment]
- An input file contains unicode.
- An input filename has unicode.
- An output file contains unicode.
- An output filename contains unicode.
- The script prints unicode to standard_output.
