### ISSUE TITLE
target_folder is shown /tmp/&tool_name/results/&number, but saves in the folder where the script lives 

### ISSUE THREAD

**Issue by AShoydokova** [crosscompute/crosscompute#10]
Windows 7, python 2.7, crosscompute-table==0.3.3

trying to save table in target_folder, but it saves in the folder where the script is.

conf.ini file is:
`[crosscompute save-table]
command_template = python save_table.py {target_folder}`

the script is:
`from os.path import join
from sys import argv
import csv
from invisibleroads_macros.disk import make_folder

target_folder = make_folder(argv[1])
target_path = join(target_folder, 'points.csv')
csv_writer = csv.writer(open(target_path, 'w'))
csv_writer.writerow(['x', 'y'])
csv_writer.writerow([100, 100])
print('point_table_path = ' + target_path)`

the output after running crosscompute run save-table:
`[tool_definition]
tool_name = save-table
configuration_path = H:/code/python/test_crosscompute/show table/conf.ini
command = python save_table.py /tmp/save-table/results/6

[result_arguments]
target_folder = /tmp/save-table/results/6

[standard_output]
point_table_path = tmpsave-tableresults6\points.csv

[result_properties]
standard_outputs.point_table_path = tmpsave-tableresults6/points.csv
execution_time_in_seconds = 4.03399991989`

**Comment by invisibleroads** [comment]
Hmm, this is serious. Thank you for highlighting this error. I will look into it.

**Comment by AShoydokova** [comment]
I created a test for that and did following:
git add -A
git commit -m 'test for target_folder'
git push

but seems it didn't push here. What should i do in order to add my test to this repository?

**Comment by AShoydokova** [comment]
ok, added a pull request with a test for the issue

**Comment by invisibleroads** [comment]
Thank you for the pull request!

Fixed in 321a1483feaf0be4c0d9231c8a9833ade3011db4
