### ISSUE TITLE
When trying to show a plot on a web, there is IOError: File does not exist

### ISSUE THREAD

**Issue by AShoydokova** [crosscompute/crosscompute#13]
Windows 7, python 2.7

When trying to replicate an example "Show images", the command below gives an error (IOError: File tmpshow-plotuploads1point_table.csv does not exist):
`crosscompute serve show-plot`

The point_table.csv file is here though tmp\show-plot\uploads\1\point_table.csv. It seems backward slashes aren't added when crosscompute is trying to post the image on the web. Could be related to issue #2 about spaces in a script name when you did shlex.split(posix=False)

Though the command
`crosscompute run show-plot`
runs without any errors and creates an image.

**Comment by invisibleroads** [comment]
As of the latest release, running the crosscompute development server is only supported in a POSIX/UNIX environment. There are no plans to support Windows at this time. Thanks for reporting this issue.
