### ISSUE TITLE
Error No such file or directory when run scripts with spaces in the script name

### ISSUE THREAD

**Issue by AShoydokova** [crosscompute/crosscompute#2]
when I run 'crosscompute run' with the following configuration files:

```
[crosscompute test]
command_template = python test v4.py
show_standard_output = True
show_standard_error = True
```

or 

```
[crosscompute test]
command_template = python 'test v4.py'
show_standard_output = True
show_standard_error = True
```

or 

```
[crosscompute test]
command_template = python "test v4.py"
show_standard_output = True
show_standard_error = True
```

I got the error: [Errno 2] No such file or directory

tried to do:
```
command_template = python ''test v4.py''
command_template = python \'test v4.py\'
```

Same error. Seems crosscompute don't know recognize spaces in the file names.
Ran on Windows 7.

**Comment by invisibleroads** [comment]
@AShoydokova, thank you so much for posting this issue! We'll aim to get this fixed by the next release, which is scheduled for April 1st. I'll keep you updated.

**Comment by invisibleroads** [comment]
Single quotes and double quotes work on Fedora 23.

**Comment by invisibleroads** [comment]
Setting shlex.split(posix=False) fixes this issue.

I'll need to test whether this works in Windows XP as well.
