### ISSUE TITLE
Can't split the command template across multiple lines on Windows

### ISSUE THREAD

**Issue by AShoydokova** [crosscompute/crosscompute#3]
Not sure if i understand it correctly, but when i put this in the .ini file:
[crosscompute test]
command_template = python run.py
{x}
{y}
show_standard_output = False
show_standard_error = False
x=10
y=3

I got these errors:

`File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\...\Envs\crosscompute\Scripts\crosscompute.exe\__main__.py", line 9, in <module>
  File "C:\Users\...\Envs\crosscompute\lib\site-packages\crosscompute\scripts\__init__.py", line 80, in launch
    run_scripts(scripts_by_name, args)
  File "C:\Users\....\Envs\crosscompute\lib\site-packages\invisibleroads\scripts.py", line 78, in run_scripts
    d = script.run(args)
  File "C:\Users\....\Envs\crosscompute\lib\site-packages\crosscompute\scripts\run.py", line 19, in run
    tool_definition = load_tool_definition(args.tool_name)
  File "C:\Users\...\Envs\crosscompute\lib\site-packages\crosscompute\scripts\__init__.py", line 87, in load_tool_de
finition
    tool_definition = get_tool_definition(tool_name=tool_name)
  File "C:\Users\....\Envs\crosscompute\lib\site-packages\crosscompute\configurations.py", line 21, in get_tool_defin
ition
    tool_folder, default_tool_name)
  File "C:\Users\...\Envs\crosscompute\lib\site-packages\crosscompute\configurations.py", line 54, in get_tool_defin
ition_by_name_from_folder
    configuration_path, default_tool_name=tool_name))
  File "C:\Users\....\Envs\crosscompute\lib\site-packages\crosscompute\configurations.py", line 63, in get_tool_defin
ition_by_name_from_path
    configuration.read(configuration_path)
  File "C:\Python27\Lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "C:\Python27\Lib\ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: H:\Code\Python\test_crosscompute\conf.ini
        [line  3]: '{x} \n'
        [line  4]: '{y}\n'
`
Below my configuration:
Windows 7, packages installed:
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
certifi==2016.2.28
colorama==0.3.7
configparser==3.3.0.post2
crosscompute==0.4.3
crosscompute-geotable==0.0.2
crosscompute-image==0.0.1
crosscompute-integer==0.3.1
crosscompute-table==0.3.3
crosscompute-text==0.3.1
cycler==0.10.0
decorator==4.0.9
dogpile.cache==0.5.7
dogpile.core==0.4.1
et-xmlfile==1.0.1
functools32==3.2.3.post2
invisibleroads==0.1.4
invisibleroads-macros==0.6.6
invisibleroads-posts==0.4.6
invisibleroads-repositories==0.1.3
ipykernel==4.3.1
ipython==4.1.2
ipython-genutils==0.1.0
ipywidgets==4.1.1
jdcal==1.2
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.2.2
jupyter-console==4.1.1
jupyter-core==4.1.0
Mako==1.0.4
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.2
msgpack-python==0.4.7
nbconvert==4.1.0
nbformat==4.0.1
notebook==4.1.0
numpy==1.10.4
openpyxl==2.3.4
pandas==0.18.0
PasteDeploy==1.5.2
path.py==8.1.2
pathlib==1.0.1
pbr==1.3.0
pickleshare==0.6
py==1.4.31
Pygments==2.1.3
pyparsing==2.1.0
pyramid==1.6.1
pyramid-debugtoolbar==2.4.2
pyramid-jinja2==2.6.2
pyramid-mako==1.0.2
pyreadline==2.1
pytest==2.9.1
python-dateutil==2.5.1
pytz==2016.2
pyzmq==15.2.0
qtconsole==4.2.0
repoze.lru==0.6
requests==2.9.1
simplegeneric==0.8.1
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.9.0
stevedore==1.6.0
titlecase==0.8.1
tornado==4.3
traitlets==4.2.1
translationstring==1.3
tzlocal==1.2.2
venusian==1.0
virtualenv==13.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.6.0
virtualenvwrapper-powershell==12.7.8
virtualenvwrapper-win==1.2.1
waitress==0.8.10
WebOb==1.6.0
wheel==0.24.0
xlrd==0.9.4
zope.deprecation==4.1.2
zope.interface==4.1.3

**Comment by invisibleroads** [comment]
Instead of parsing error, `crosscompute run` should generate a more information error message that tells the user to indent for multiple lines. I'll fix this today.

**Comment by invisibleroads** [comment]
crosscompute 0.9 supports YAML configuration.

[Multi-line strings require slightly different syntax in YAML](https://yaml-multiline.info).

For a multi-line command, you can see `run5.py` in [this example](https://github.com/crosscompute/crosscompute/blob/develop/crosscompute/templates/configuration.yml#L169):

```
scripts:
  - path: run1.py
  - path: run2.py
    folder: scripts
  - path: run3.ipynb
  - command: python run4.py {input_folder} {output_folder}
  - command: >
      python run5.py
      {input_folder} {output_folder} {log_folder} {debug_folder}
```
