### ISSUE TITLE
The tool scaffold can't clone the basic tool scaffold

### ISSUE THREAD

**Issue by AShoydokova** [crosscompute/crosscompute#4]
Windows 7, python 2.7, crosscompute0.4.3

When I do a command: `pcreate -s tool your-tool-name`. I got this error:

WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\&username\\Envs\\crosscompute\\lib\\site-pa
ckages\\crosscompute\\scaffolds\\tool/*.*'

I looked at the folder:C:\Users\&user\Envs\crosscompute\Lib\site-packages\crosscompute\scaffolds there is no tool folder either.

**Comment by salah93** [comment]
mac os, python2.7, crosscompute0.4.4

when creating a scaffold for template profile "tool" only cc.ini file showing

**Comment by invisibleroads** [comment]
Thanks @AShoydokova and @salah93, this is fixed in the latest branch and should be on PyPI by Tuesday: https://github.com/crosscompute/crosscompute/tree/0.4.5

```
git clone https://github.com/crosscompute/crosscompute
git checkout -t origin/0.4.5
python setup.py develop
cd ~/Experiments/crosscompute
pcreate -s tool xyz
```

@Jenniferrrr
