### ISSUE TITLE
Uninstall Script

### ISSUE THREAD

**Issue by kashfifahim** [crosscompute/crosscompute#49]
When a user wishes to uninstall CrossCompute from their machine, can we also remove all the InvisibleRoads packages?

**Comment by invisibleroads** [comment]
There is no straightforward way to remove unused dependencies using `pip`.
https://stackoverflow.com/questions/57470523/pip-uninstall-package-and-unique-dependencies

There was some debate about whether to package all the macros into crosscompute or separate them and use the invisibleroads-macros-* packages. I think separate packages will result in greater reusability for the macros and a smaller test coverage surface area for crosscompute.

I thought about making a simple uninstall script but it could break other packages that rely on the dependencies.

The recommendation is to install in a virtual environment.
